### ISSUE TITLE
Internet Explorer 9 support?

### ISSUE THREAD

**Issue by terhechte** [martinklepsch/s3-beam#11]
Is there an easy way to add IE9 support to this? Particularly support for input type-file and not just drag and drop. I've looked into a couple of polyfills, but none of them seems to enable that. Most promising seems to be dropfile.js but it lists on-changed support for file inputs as a TODO.

**Comment by martinklepsch** [comment]
Maybe some stuff from google closure could help with that?

**Comment by terhechte** [comment]
There's iframeio (https://closure-library.googlecode.com/git-history/docs/class_goog_net_IframeIo.html) which does the old school iframe reloading trick to have javascript uploads without page reloading form submission, but I'm not sure if it'll allow to access the filename / size that is required to properly sign the file.

**Comment by martinklepsch** [comment]
Until now I didn't need to make it work with IE9 so I'm afraid I can't really help. If you find a good way to make it work I'd definitely be interested in adding it though :)

**Comment by terhechte** [comment]
Ok, I thought I'd at least ask, hoping that maybe you did already solve this :) Based on my research it is a bit difficult to achieve, and I suppose it's not really worth the time given the little market share IE9 has. I'll close this :) thanks anyway!

**Comment by martinklepsch** [comment]
That makes sense too. Sorry I couldn't be of more help :)
