### ISSUE TITLE
readme needs adjument? (custom signing url)

### ISSUE THREAD

**Issue by JulianLeviston** [martinklepsch/s3-beam#12]
There's a custom URL in the source (: server-url in opts), but the readme currently lists custom signing url as being one of the nice to haves. Or, have I missed something here? Readme should be updated if I haven't missed anything.

Also, how is upload progress coming along? or not?

**Comment by martinklepsch** [comment]
Hi Julian, you're right. We added the addition of the `:server-url` option to the changelog but didn't adapt the rest of the readme. PR syncing those things up would be very welcome! :)

**Comment by JulianLeviston** [comment]
@martinklepsch ok, I did a tiny PR. I think this is all that's required - I realised the readme already references the custom server URL.
