### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by danielcompton** [martinklepsch/s3-beam#33]
We've been using 0.5.2-alpha2 for a while, can we cut an 0.5.2 release?

**Comment by martinklepsch** [comment]
Just deployed `0.5.2` to Clojars — for completeness the changelog should be updated 👍

**Comment by danielcompton** [comment]
I've updated with changes for 0.5.2. I didn't really understand what happened with git history before that though?

**Comment by martinklepsch** [comment]
Not Entirely sure but it might be I haven't cut a 0.5.0 release because the version bumb was made in a PR and the commit has never been HEAD of this repo. Probably best to update the changelog to refer to 0.5.1? (0.5.0 does not exist tagged nor on clojars)
