### ISSUE TITLE
Add support for Signature Version 4

### ISSUE THREAD

**Issue by whamtet** [martinklepsch/s3-beam#34]
AWS Signature Version 4 is the only supported version for new buckets such as Seoul (ap-northwest-2), you should add support for this.

[Doco](http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html#signing-request-intro)

**Comment by martinklepsch** [comment]
A pull request is welcome.

**Comment by whamtet** [comment]
Ok,

let me figure this out and I'll send it through.

Matt

**Comment by whamtet** [comment]
Version 4 is supported by [s3-beamer](https://github.com/whamtet/s3-beamer)
