### ISSUE TITLE
JavaScript Equivalent

### ISSUE THREAD

**Issue by lgleim** [martinklepsch/s3-beam#41]
Is it possible to use s3-beam in JavaScript or even TypeScript applications? If not, are you aware of a similar JavaScript project?

**Comment by martinklepsch** [comment]
Sorry but that's not in the scope of this library :)

I remember there being a few jquery approaches but in any case it's a client and server problem so you'll need to find something where both parts work together properly, good luck! 🍀

**Comment by martinklepsch** [comment]
Sorry but that's not in the scope of this library :)

I remember there being a few jquery approaches but in any case it's a client and server problem so you'll need to find something where both parts work together properly, good luck! 🍀
